version: '3'
services:
        app:
                build:
                        context: .
                        dockerfile: .docker/Dockerfile
                ports:
                        - "8000:8000"
                networks:
                        - facexam_network
        web:
                build:
                        context: ./.docker
                        dockerfile: nginx/Dockerfile
                volumes:
                        - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "9000:80"
                links:
                        - app
                networks:
                        - facexam_network
networks:
        facexam_network:
                driver: "bridge"
